version: '2.1'

services:
  test:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/hmcts-test/test-template-143/test
    ports:
      - $SERVER_PORT:$SERVER_PORT
